name: Sign artifact
description: 使用 SignPath 对指定工件中的文件进行签名并回传签名工件

inputs:
  manifest_artifact:
    description: 需要签名的清单工件名称
    required: true
  executable_name:
    description: 清单中需要签名的文件名
    required: true
  signpath_api_token:
    description: SignPath API Token
    required: true

outputs:
  signed_executable_artifact:
    description: 签名后的工件名称
    value: ${{ steps.set-output.outputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: Download manifest artifact
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.manifest_artifact }}
        path: ./manifest

    - name: Expand ZIP artifacts if present
      shell: pwsh
      run: |
        $zipFiles = Get-ChildItem -Path ./manifest -Filter '*.zip' -Recurse -ErrorAction SilentlyContinue
        if ($zipFiles -and $zipFiles.Count -gt 0) {
          New-Item -ItemType Directory -Path ./manifest_extracted -Force | Out-Null
          foreach ($zf in $zipFiles) {
            try {
              Expand-Archive -Path $zf.FullName -DestinationPath ./manifest_extracted -Force
            } catch {
              Write-Host "[DEBUG] ZIP 解压失败: $($zf.FullName) — $($_.Exception.Message)"
            }
          }
        } else {
          Write-Host "[DEBUG] 未发现 ZIP 工件，跳过解压"
        }

    - name: Prepare file for signing
      shell: pwsh
      run: |
        $exe = $null
        if (Test-Path './manifest_extracted') {
          $exe = Get-ChildItem -Path ./manifest_extracted -Filter "${{ inputs.executable_name }}" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        }
        if ($null -eq $exe) {
          $exe = Get-ChildItem -Path ./manifest -Filter "${{ inputs.executable_name }}" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        }
        if ($null -eq $exe) { Write-Error "未找到待签名文件: ${{ inputs.executable_name }}"; exit 1 }
        New-Item -ItemType Directory -Path ./exe-for-signing -Force | Out-Null
        Copy-Item $exe.FullName -Destination "./exe-for-signing/${{ inputs.executable_name }}" -Force

    # - name: Upload unsigned artifact
    #   id: upload-unsigned
    #   uses: actions/upload-artifact@v5
    #   with:
    #     name: ${{ inputs.executable_name }}-signed
    #     path: ./exe-for-signing

    - name: Submit signing request
      id: submit-sign
      uses: signpath/github-action-submit-signing-request@v2
      with:
        api-token: ${{ inputs.signpath_api_token }}
        organization-id: 2e13633d-4e7d-4462-9091-27536751c84c
        project-slug: Class-Widgets.git
        signing-policy-slug: release-signing
        github-artifact-id: ${{ steps.upload-unsigned.outputs.artifact-id }}
        wait-for-completion: true
        output-artifact-directory: ./signed-output

    # - name: Upload signed artifact
    #   id: upload-signed
    #   uses: actions/upload-artifact@v5
    #   with:
    #     name: ${{ inputs.executable_name }}-signed
    #     path: ./signed-output

    - name: Set outputs
      id: set-output
      shell: pwsh
      run: |
        "$env:GITHUB_OUTPUT" | Out-Null
        Write-Output "artifact-name=${{ inputs.executable_name }}-signed" >> $Env:GITHUB_OUTPUT
