name: 构建

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'

      - name: 创建虚拟环境
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install -r requirements.txt
          pip install requests
          pip install pyinstaller

      - name: 使用 PyInstaller 打包
        run: |
          .\venv\Scripts\activate
          pyinstaller main.py -w -i ./img/favicon.ico -n ClassWidgets

      - name: 复制依赖和资源
        run: |
          xcopy /E /I config .\dist\Class-Widgets\config
          xcopy /E /I ui .\dist\Class-Widgets\ui
          xcopy /E /I img .\dist\Class-Widgets\img
          xcopy /E /I audio .\dist\Class-Widgets\audio
          copy *.ui .\dist\ClassWidgets\

      - name: 存到构建输出
        uses: actions/upload-artifact@v4
        with:
          name: Windows-amd64
          path: ./dist/ClassWidgets/
