name: 构建

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  builder_matrix:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
        os: [ubuntu-20.04, windows-latest, macos-13]
        exclude:
          - os: ubuntu-20.04
            arch: x86
          - os: macos-13
            arch: x86
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.8.10'
          architecture: ${{ matrix.arch }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
      - name: Run Windows build
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          uv venv
          .venv\Scripts\activate
          uv pip install -r requirements.txt
          uv pip install pyinstaller
          pyinstaller main.py `
            -w `
            -i ./img/favicon.ico `
            -n ClassWidgets `
            --contents-directory . `
            --add-data config:config `
            --add-data audio:audio `
            --add-data img:img `
            --add-data ui:ui `
            --add-data font:font `
            --add-data *.ui:. `
            --add-data LICENSE:. `
            --add-data plugins:plugins
      - name: Run Linux build
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r  requirements.linux.txt
          uv pip install pyinstaller
          pyinstaller main.py \
            -w \
            -i ./img/favicon.ico \
            -n ClassWidgets \
            --contents-directory . \
            --add-data config:config \
            --add-data audio:audio \
            --add-data img:img \
            --add-data ui:ui \
            --add-data font:font \
            --add-data *.ui:. \
            --add-data LICENSE:. \
            --add-data plugins:plugins \
            --hidden-import numpy

      - name: Run macOS build
        if: ${{ matrix.os == 'macos-13' }}
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r  requirements.linux.txt
          uv pip install pyinstaller
          pyinstaller main.py \
            -w \
            -i ./img/favicon.icns \
            -n ClassWidgets \
            --contents-directory . \
            --add-data config:config \
            --add-data audio:audio \
            --add-data img:img \
            --add-data ui:ui \
            --add-data font:font \
            --add-data *.ui:. \
            --add-data LICENSE:. \
            --add-data plugins:plugins \
            --hidden-import numpy
          mkdir dist-bundle
          cp -r "dist/ClassWidgets.app" "dist-bundle/Class Widgets.app"
      - name: Upload
        uses: actions/upload-artifact@v4.4.2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: ./dist/
      - name: Upload macOS Bundle
        uses: actions/upload-artifact@v4.4.2
        with: 
          name: macos-13-x64-bundle
          path: ./dist-bundle/

  debian10:
    runs-on: ubuntu-latest
    container: debian:10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
    - name: Setup uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: '3.8.10'
    - name: Install dependencies
      run: |
        apt update
        apt install binutils -y
    - name: Run build
      shell: bash
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -r  requirements.linux.txt
        uv pip install pyinstaller
        pyinstaller main.py \
          -w \
          -i ./img/favicon.ico \
          -n ClassWidgets \
          --contents-directory . \
          --add-data config:config \
          --add-data audio:audio \
          --add-data img:img \
          --add-data ui:ui \
          --add-data font:font \
          --add-data *.ui:. \
          --add-data LICENSE:. \
          --add-data plugins:plugins \
          --hidden-import numpy
    - name: Upload
      uses: actions/upload-artifact@v4.4.2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}
        path: ./dist/